### ISSUE TITLE
Setting DSYM_PATH before executing script has issues

### ISSUE THREAD

**Issue by k-shan** [Instabug/Instabug-iOS#166]
Instabug_dsym_upload.sh script doesn't use DSYM_PATH if it's set prior to script execution (specifically this [line](https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.framework/Instabug.bundle/Instabug_dsym_upload.sh#L85))

**Comment by Figo0o** [comment]
Hello @k-shan, I really don't get the problem. Can you please provide me more details about whats happening?

**Comment by k-shan** [comment]
Sure, on this [line](https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.framework/Instabug.bundle/Instabug_dsym_upload.sh#L62) the script checks `$DSYM_PATH` and sets it if it doesn't exits. However on the [line mentioned above](https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.framework/Instabug.bundle/Instabug_dsym_upload.sh#L85) it's using a different variable. You just need to update that line with `$DSYM_PATH`.

**Comment by Figo0o** [comment]
Well, Thanks for you feedback we appreciate that so much. 

Actually we can't replace [this line](https://github.com/Instabug/Instabug-iOS/blob/master/Instabug.framework/Instabug.bundle/Instabug_dsym_upload.sh#L85) with `$DSYM_PATH` because here we are trying to find all dSYM files found there in that directory to upload them to the dashboard (depends on if you have any other inner frameworks or not) and `DSYM_PATH` is only a path for the application's dSYM. 

Please let me know if you have more comments. Thanks!
