### ISSUE TITLE
Unable to install with Cocoapods

### ISSUE THREAD

**Issue by lauracpierre** [Instabug/Instabug-iOS#22]
Hi Guys, 

I tried to install your SDK with Cocoapods. We are using Swift 1.2 at the moment. 
Just did pod 'Instabug' and it installed it correctly. 

When I try to import the framework in the AppDelegate, it says "No such module 'Instabug'"

Digging a bit further, in the Pod project, there is no target Instabug like the other pod I'm using. 
![image](https://cloud.githubusercontent.com/assets/979311/8371290/4447b726-1b8a-11e5-9e99-f947d898c92c.png)

Any help greatly appreciated. 

Thanks !

**Comment by msoliman** [comment]
Not seeing it in the targets is probably a cocoapods error, you can just do another `pod install` to get it done.

However, to be able to use our SDK with Swift, you'll need to have a bridging header (because our SDK is written in ObjC).
Here's how to do it:
1. Create a new file, call it “bridging-header.h”. And import Instabug in there: 
#import <Instabug/Instabug.h> 
2. In your Build Settings, set the “Objective-C Bridging Header” property to the location of the file you’ve created: 
"{directory}/bridging-header.h" 

Once you do so, you should be able to use Instabug’s SDK in your Swift app. 
Please let me know if you need any help setting this up. I can provide more details about this.

**Comment by lauracpierre** [comment]
Unfortunately I already tried the bridging header, sorry for not mentioning it. 
Still the error persists. (and I have done multiple pod install already)

**Comment by msoliman** [comment]
That's probably a Cocoapods error. Did you manage to fix it already?

If not, can you try to integrate the SDK manually and see if it works?

**Comment by nassarofficial** [comment]
[Instabug startWithToken:@"8bf991235ff10a1897e63146cccca07b" captureSource:IBGCaptureSourceUIKit invocationEvent:IBGInvocationEventShake]; what does it become in swift?

**Comment by nassarofficial** [comment]
Instabug.startWithToken("string", captureSource:IBGCaptureSourceUIKit, invocationEvent:IBGInvocationEventShake)
for swift.

**Comment by gabro** [comment]
I can reproduce the same issue, after running `pod install` the Instabug framework is not added to the Pods project target. All the other Pods work fine in my project.

Here's a demo project that reproduces this issue: https://github.com/buildo/Instabug-CocoaPods

@msoliman can you please look into this?

**Comment by msoliman** [comment]
@gabro I've downloaded the project and ran `pod install`. The Instabug pod was added successfully.
However, the build failed because you're not adding a bridging header to import Instabug's SDK into Swift.

Was this the error you were getting?

To fix this, you'll need to [add the bridging header](https://github.com/Instabug/Instabug-iOS/issues/22#issuecomment-115650718), and remove the `import Instabug` from your AppDelegate.

Let me know how it goes.

**Comment by gabro** [comment]
Ok, it works when importing it in the bridging header with

```objc
#import <Instabug/Instabug.h>
```

However, by using the `use_frameworks` option, we should be able to use it as a module and do either

```objc
@import Instabug;
```

or simply

```swift
import Instabug
```

without the need for bridging header.

Any idea of why this isn't working as expected?

**Comment by msoliman** [comment]
@gabro That's true, this is because we support lower versions of iOS (iOS 5 and 6) in the same slice.
However, in our next release, we'll changing this by having a separate slice for iOS 7+ which will allow you to use it with `use_frameworks` option.

This should be out later this month. Is this blocking you at the moment?

**Comment by gabro** [comment]
Definitely not blocking, I'll simply add a bridging header and call it a day.

If you can update this thread once the update is out, I'd very much appreciate it.

In the meantime, thanks for the prompt support!

**Comment by cameronbell** [comment]
I'm having the same issue where cocoapods isn't creating a target for the Instabug cocoapod in the Pods project, except I'm not using swift. 

Naturally the  `#import <Instabug/Instabug.h>` call isn't working. 

I tried both:
`pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script'`
and
`pod 'Instabug', '~> 4.1'`

Any idea what the problem might be?

**Comment by msoliman** [comment]
@cameronbell my first guess would be that this might be Cocoapods issue. Which version are you using?

I can help much more if you can reproduce this in a sample app and just send it over to me. And I'll dig deeper into it.

**Comment by kyramckenna** [comment]
Yes I'm having the same issue. Just deleting everything and trying again

**Comment by cameronbell** [comment]
Re-cloning my entire project solved the problem. I couldn't figure out what was causing the headers to not be available.

**Comment by timbroder** [comment]
I had this issue and ```pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script'``` fixed it for me

Though it did downgrade from 5.1.2 to 5.1.0

**Comment by msoliman** [comment]
@timbroder interesting, thanks for letting me know. I've updated `no_build_script` so it should be on 5.1.2 now

**Comment by timbroder** [comment]
@msoliman interestingly enough, that broke it
this works
```    pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script', :commit => '681d778c76e1d6570501c14bfd11dc8511525cd1'```

these do not

```pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script', :commit => 'd04a04f881ce9b4f2f8910dd1ed390fa7219bd1e'```

```pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script'```

**Comment by msoliman** [comment]
@timbroder that's interesting. Can you try re-running pod install again? Also to make sure, this doesn't happen when you integrate the SDK manually, right?

**Comment by irace** [comment]
@msoliman Is it still not possible to import the Instabug framework without a bridging header?

**Comment by benfwirtz** [comment]
I still have the problem but can't get it fixed with the above suggestions.
- I use a bridging header for various other frameworks, and it seems to work, but the Instabug class reference in the AppDelegate's didLaunchWithOptions function doesn't get recognised ("use of unresolved identifier 'Instabug'").
- Neither adding nor removing "import Instabug" makes a difference.

In another thread it was suggested to add Instabug manually to the "Link Binary With Libraries" section, but although the pod is installed and built (no complaints about the bridging header), Instabug does not show up anywhere in the frameworks list - unlike all other pods I use.

I have tried several cleans, pod installs, deleting the xcworkspace file, restarting my machine, upgrading cocoapods and re-installing all pods again. I'm using Swift and the app is compatible down to iOS 8.1 - what am I missing?

**Comment by paulshapiro** [comment]
I also encountered this issue. I'm concerned by the lack of proper response.

**Comment by msoliman** [comment]
@irace @benfwirtz @paulshapiro Sorry for the delay in getting back to you.
So we've recently updated our SDK adding module map support. So you won't need to add a bridging header now. Just add `use_framewords!` to your pod file and import Instabug right away into your App Delegate.

Please let me know how it goes.

**Comment by timbroder** [comment]
Confirming I no longer need this to install Instabug via cocoapods

```
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script', :commit => '681d778c76e1d6570501c14bfd11dc8511525cd1'
```

This works:

```
pod 'Instabug'
```

```
Installing Instabug 5.3.2 (was 5.1.1)
```

**Comment by zrxq** [comment]
Had the same issue, deleted Pods and Podfile.lock, reinstalled, worked.

This is what's changed:

```
z:iKasta zoreslav$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	typechange: Pods/Instabug/Instabug.framework/Instabug

z:iKasta zoreslav$ git commit
[master ccd695b] Instabug framework mode fixed
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite Pods/Instabug/Instabug.framework/Instabug (100%)
 mode change 120000 => 100755
```

`¯\_(ツ)_/¯`
