### ISSUE TITLE
IBG methods are executed on main thread when scroll in collection view

### ISSUE THREAD

**Issue by xiaomaogong** [Instabug/Instabug-iOS#26]
<img width="591" alt="screen shot 2015-08-13 at 7 43 51 pm" src="https://cloud.githubusercontent.com/assets/9329201/9249058/0ba83162-41f4-11e5-908a-aa6af0a1ed6d.png">

Our collection view 's scroll performance are considerably impact by the [IBGMethodSwizzier sendEvent:] , any idea how to solve this?

**Comment by msoliman** [comment]
@xiaomaogong can you please expand this call and resend me a screenshot?
The thing is that we do replace the `[UIApplication sendEvent:]` method with our own `[IBGMethodSwizzler sendEvent:]` which logs the event and then recalls the original implementation of `[UIApplication sendEvent:]`. So that time might be in either our logging code or in the UIApplication's implementation. Does that make sense to you?

**Comment by xiaomaogong** [comment]
<img width="728" alt="screen shot 2015-08-13 at 7 58 15 pm" src="https://cloud.githubusercontent.com/assets/9329201/9249285/f89bb9e8-41f5-11e5-9ed7-e01992a3f612.png">

**Comment by msoliman** [comment]
@xiaomaogong ok, so let's disable UserSteps logging and see if this changes. Just add `[Instabug setIsTrackingUserSteps: NO];` to your initialization code. Let me know how it goes.

**Comment by xiaomaogong** [comment]
It looks like much better now , but any side effect after adding [Instabug setIsTrackingUserSteps: NO];?

**Comment by msoliman** [comment]
@xiaomaogong yes, this will stop the UserSteps being logged. I can have a workaround for this by disabling the view introspection and send you a custom version of the SDK. In that case you'll be getting the UserSteps without that overhead in performance.
How does this sound for you?
