### ISSUE TITLE
The action sheet appeared after almost 10 seconds when I shook the simulator.  

### ISSUE THREAD

**Issue by luohui8891** [Instabug/Instabug-iOS#28]
Hi @msoliman 
I have upgraded the Instabug to 4.1.5 via pods.
First I tested on the simulator, I chose Hardware->Shake Gesture to report feedback. But the action sheet appeared ("Report a bug", "Send feedback", "Cancel") after almost 10 seconds.
But it worked fine on the device.

Do you have any idea?

**Comment by msoliman** [comment]
@luohui8891 That's probably because you've been using this simulator for too long.
The thing is that the iOS simulator caches all the console log on your mac since the first time you’ve installed the iOS simulator, so when Instabug’s SDK tries to grab the console log, it had to look through tons of console logs and that’s why it takes too much. This doesn’t happen on the device because the device automatically deletes old console logs.

If you want to delete the old console logs you have on your simulator, just go to the folder ~/Library/Logs/CoreSimulator/, then select the simulator you’re using, and delete the contents of the “asl" folder.

After doing so, you should be able to get everything working properly. Let me know how it goes.

**Comment by luohui8891** [comment]
@msoliman that's it. Thank you very much.
But I noticed another flash issue on simulator.
See the following GIF, I have turned on the slow animation. BTW, I can't reproduce it on device.
![2015-08-31 at 5 13](https://cloud.githubusercontent.com/assets/1223339/9575625/af6eb33a-5003-11e5-9512-76a24a9ea923.gif)

**Comment by msoliman** [comment]
@luohui8891 I believe this has always been there. It should be fixed as part of our next release, as it'll include a new design as well.
Let me know if you were able to reproduce it on device, in that case we'll need to release a hot-fix for it.
How does this sound for you?

**Comment by luohui8891** [comment]
@msoliman it's cool. You guys are fast.
