### ISSUE TITLE
Apple rejected the App because of the custom screenshot

### ISSUE THREAD

**Issue by HebaAtallah** [Instabug/Instabug-iOS#306]
I've sent an explanation of the custom screenshot to Apple when the App got rejected for the first time, but they have been rejecting it for the second time for the same reason.

<img width="813" alt="screen shot 2019-01-17 at 9 24 01 pm" src="https://user-images.githubusercontent.com/6685615/51343419-0f47d980-1a9f-11e9-9399-6eb5167223a2.png">

**Comment by Kmohamed** [comment]
Are you invoking Instabug using screenshot?

**Comment by HebaAtallah** [comment]
Yes, `IBGInvocationEventScreenshot` should I remove that?
If yes, Instabug will be able to take a screenshot when the device gets the shake?

**Comment by Kmohamed** [comment]
Yes, just replace it with shake and Instabug will continue capturing screenshot

**Comment by gilroykilroy** [comment]
Good to know this is a reject-able “feature” since that is what I had chosen for my soon to be submitted app. I am switching to two finger left swipe since shake is “undo” which my app has (and may also get rejected for bringing up Instabug since https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/gestures/ says “Avoid using standard gestures to perform nonstandard actions”).

**Comment by Kmohamed** [comment]
@gilroykilroy @HebaAtallah I am sorry to hear that but we will try hard to find different invocation methods.
