### ISSUE TITLE
Appstore Rejection

### ISSUE THREAD

**Issue by jayarajb1116** [Instabug/Instabug-iOS#317]
Guideline 4.0 - Design

We noticed that your app offers a custom screenshot-initiated interface when the user takes a screenshot in the app.

**Comment by msoliman** [comment]
@jayarajb1116 that's weird. Can you please share the SDK initialization code? which invocation gesture are you using?

**Comment by jayarajb1116** [comment]
```
        // Configure Instabug to track the crashes and feedbacks from customers
        Instabug.start(withToken: APIConstants.shared.instabugToken, invocationEvents: [.shake, .screenshot])
        if (self.isRunningLive()) {
            Instabug.start(withToken: APIConstants.shared.instabugToken, invocationEvents: [.shake, .screenshot])
        } else {
            Instabug.start(withToken: APIConstants.shared.instabugToken, invocationEvents: [.shake, .screenshot])
        }
        // Disabled instabug welcome popup
        Instabug.welcomeMessageMode = .disabled
        // Setup number of time shaking to show bug report popup
        BugReporting.shakingThresholdForiPhone = 3
        BugReporting.shakingThresholdForiPad = 2
```

**Comment by jayarajb1116** [comment]
Hi @msoliman 

Same issue was posted by an user in the below link
[(https://github.com/Instabug/Instabug-iOS/issues/306)]

**Comment by msoliman** [comment]
Can you try removing the `.screenshot` from the `invocationEvents`?

While it is mentioned in the guidelines, we rarely encounter rejection cases because of the screenshot invocation gesture. However, in the very few cases that we received, usually changing the invocation event to *two-fingers swipe*, *shake*, or *right edge pan* was enough to pass the review. You can find more details here: https://docs.instabug.com/docs/ios-invocation#section-invocation-events

Would you mind sharing with me whether this is the first time you submit the app to the store or it is just an update review?

**Comment by jayarajb1116** [comment]
@msoliman 
We already uploaded so many builds with screenshot enabled to Appstore. And app was approved before. But not this time.
I've removed .screenshot and uploaded to AppStore and it's waiting for review now.
But we really need that screenshot feature. 
Is there any possibility to avoid rejection?

**Comment by jamesatfish** [comment]
Adding our +1 to this same issue thread.

We have been using Instabug with the screenshot invocation for about 9 months, no issues until an otherwise minor dot point update about 2 weeks ago, at which point the app was rejected siting the same Guideline 4.0.

The only way we could have the update approved was to remove the screenshot invocation from our Instabug config.

**Comment by anaseem80** [comment]
have you solved the issue?

**Comment by EyadHeikal** [comment]
@anaseem80 Hey Ahmed, It's still not recommended to use screenshot invocation event on live builds as it can cause Appstore rejection.

**Comment by anaseem80** [comment]
Hello! But i was typed a native code that make screenshot disabled but I
deleted it so can you please send me screenshot please for the problem
because I did not get this problem will please help me

**Comment by ahmedsalah196** [comment]
Hello @MujibBasha,
We’re not expecting this to be solved as it’s not a technical issue from our side to fix. Apple is refusing the feature itself as its overriding the default screenshot behavior. This leaves us with no workarounds to enable this in production

Let me know if I can be of any help
