### ISSUE TITLE
Instabug Still Taking Screenshots When trackUserSteps = NO and reproStepsMode = IBGUserStepsModeDisable

### ISSUE THREAD

**Issue by bdaz** [Instabug/Instabug-iOS#340]
I first found this issue when profiling my app, because I recently started seeing huge frame drops on view controller transitions. Profiling revealed it was mostly Instabug.

### Steps to Reproduce the Problem
```
Instabug.reproStepsMode = IBGUserStepsModeDisable;
Instabug.trackUserSteps = NO;
```

### Expected Behavior
I shouldn't see console logs about Instabug taking screenshots. And I shouldn't see heavy stack traces due to screenshotting.

### Actual Behavior
Still seeing logs like this: `[Instabug] - IBGUser Steps - Captured screenshot using currentImageContext = <UIImage:0x282273e70 anonymous {375, 812}>`

### Instabug integration code
```
[Instabug startWithToken:<token> invocationEvents:IBGInvocationEventShake];

// Rage shake.
IBGCrashReporting.enabled = NO; // disable crash reporting, which is done via Crashlytics.
Instabug.welcomeMessageMode = IBGWelcomeMessageModeDisabled;
Instabug.reproStepsMode = IBGUserStepsModeDisable;
Instabug.trackUserSteps = NO;
```

### SDK Version
8.7.3

### iOS Version
13.2. Reproduces on iOS 13.1.

### Device Model
iPhone 11 Pro (reproduces on other devices as well)

**Comment by Kmohamed** [comment]
Could double check that you call them after startWithToken 🙏

**Comment by bdaz** [comment]
@Kmohamed Yeah, they are set after +startWithToken. Sorry for the empty report earlier, hit post too soon.

**Comment by Kmohamed** [comment]
Let me check it and get back to you soon

**Comment by bdaz** [comment]
I spent some more time investigating this to the point where I completely disabled (and unlinked) Instabug and I was still seeing screenshots captured—which isn't possible. Turns out this was a build cache issue (maybe because of Xcode 11.2, which was just released today).

Can confirm, setting `IBGUserStepsModeEnabledWithNoScreenshots` works as expected.

That said, I would *strongly* suggest making `IBGUserStepsModeEnabledWithNoScreenshots` the default. Screenshotting every VC transition is tremendously slow—over 500ms on an iPhone 11 Pro—and frankly I was shocked to find out screenshots were being taken without opting into it, so this is a privacy issue waiting to happen…

Appreciate any time you took to investigate so far. Keep up the great work with Instabug.

**Comment by Kmohamed** [comment]
Thanks, @bdaz for spending time debugging the issue. I agree with you that making capture screenshots is the default option is a privacy issue. But we worked around this by adding a consent. But if you saw that this is not enough. I can set up a call with one of our product managers to discuss this security is one of our top priorities.

Related to a performance issue in the transition. Yes, unfortunately, It slows down the transition in some cases and we are aware of this. It was a big challenge because we need to capture the screenshot on `main thread` without affecting the performance but finally, we found a safe way to implement this and will be in the next released.

![Simulator Screen Shot - iPhone 11 - 2019-11-01 at 08 38 16](https://user-images.githubusercontent.com/1115748/68007126-521c1c00-fc83-11e9-87c3-f588910eecd7.png)
![Simulator Screen Shot - iPhone 11 - 2019-11-01 at 08 38 20](https://user-images.githubusercontent.com/1115748/68007128-521c1c00-fc83-11e9-9f57-63c9a16970e2.png)

**Comment by leethree** [comment]
we recently ran into the issue with Instabug taking screenshots for every React-Native Modal on main thread. It causes a delay for all dialogs/popovers. 

> It was a big challenge because we need to capture the screenshot on main thread without affecting the performance but finally, we found a safe way to implement this and will be in the next released.

@Kmohamed could you elaborate on it? I haven't found any mention in the release notes. it would be great if we can upgrade and fix the issue. thanks!

**Comment by Kmohamed** [comment]
Can you open ticket on support at Instabug site?
