### ISSUE TITLE
Can you add a callback when user has dismiss the feedback window?

### ISSUE THREAD

**Issue by X140Yu** [Instabug/Instabug-iOS#39]

**Comment by msoliman** [comment]
@X140Yu what do you plan to use this for?
We already have the `[Instabug setPreSendingBlock:]`, does this fulfill your need?

**Comment by X140Yu** [comment]
What if user click cancel? Can I get a notification too?

**Comment by msoliman** [comment]
@X140Yu ok, now I understand what you need.
Well the `setPreSendingBlock` is called only when the report is submitted. But we do plan to add that one in our next release.

Is this currently blocking you?

**Comment by X140Yu** [comment]
Not that emergency, I can wait for the next release, thanks!

**Comment by MakeMeBetter** [comment]
Could you clarify when you plan to do this feature ?
Because we detect some weird scenario: [UIWindow makeKeyAndVisible] of previous UIWindow object not called after tapping Cancel Button. 
So in our app we see white screen instead of UIWindow content that was before.
And now we can`t find some triggers when you do this magic, so we are suffering now..

**Comment by alliamin** [comment]
@X140Yu @MakeMeBetter You can use `setPreInvocationBlock` and `setPostInvocationBlock` that are executed before and after SDK invocation respectively.
