### ISSUE TITLE
NetworkLogger.setResponseObfuscationHandler results in No Response Status Code 0 in Instabug

### ISSUE THREAD

**Issue by IsaiahJTurner** [Instabug/Instabug-iOS#417]
```swift
NetworkLogger.setResponseObfuscationHandler { (data, response, completion) in
			var modifiedData: Data = Data()
			let modifiedResponse: URLResponse = URLResponse.mutableCopy() as? URLResponse ?? URLResponse()
			if let sessionId = SessionManager.shared.sessionId {
				let obfuscatedSessionId = sessionId
					.replacingOccurrences(
						of: "[0-9A-Za-z]",
						with: "*",
						options: .regularExpression,
						range: nil
					)
				if let data = data, let dataString = String(data: data, encoding: .utf8) {
					modifiedData = dataString
						.replacingOccurrences(of: sessionId, with: obfuscatedSessionId)
						.data(using: .utf8) ?? Data()
				}
			}
			completion(modifiedData, modifiedResponse)
		}
```
<img width="864" alt="image" src="https://user-images.githubusercontent.com/3732588/117351838-0db6a100-ae63-11eb-94ba-2d167a4e625b.png">

**Comment by hassaanelgarem** [comment]
Hey @IsaiahJTurner 
It looks like you're creating an empty response object every time and you pass back to the completion handler, that's why on the dashboard it shows that there's no response.

You can do one of two things, either pass the `response` object as it is, as I can see you don't actually obfuscate anything in the response. This way your last line should be like that:
```swift
completion(modifiedData, response)
```
Or if you want to modify the response, then you should replace the line where you copy the response with this:
```swift
let modifiedResponse: URLResponse = response.copy(with: .none) as? URLResponse ?? URLResponse()
```
Hope this helps 👍
