### ISSUE TITLE
Instabug 1.5.x breaks the debugger

### ISSUE THREAD

**Issue by ashiemke** [Instabug/Instabug-iOS#422]
### Steps to Reproduce the Problem

When running debugger in Xcode e.g. `po <some var>` I get this error: 
``` 
virtual filesystem overlay file  '/Users/distiller/Library/Developer/Xcode/DerivedData/Instabug-cvgnxykmqaptlvcvhwtspqfbequo/Build/Intermediates.noindex/ArchiveIntermediates/InstabugDynamic/IntermediateBuildFilesPath/Instabug.build/Release-iphonesimulator/InstabugDynamic.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

This happens when using the 1.5.x SDK through cocoa pods. Downgrading to 1.4.4 fixes the issue.

xcode: 12.4
macos: 10.15.7
cocoapods: 1.10.1

Looks like a recurrence of https://github.com/Instabug/Instabug-iOS/issues/368

**Comment by husseinkishk** [comment]
Hi @ashiemke 
This is an issue in lldb, which happens sometimes when you are trying to integrate Instabug in a Swift-only project.

A workaround for this issue is to add Objective-C files and a bridging header to your project, like mentioned in this [StackOverflow post](https://stackoverflow.com/questions/54776459/whats-the-solution-for-error-couldnt-irgen-expression-no-additional-error/61824142#61824142).

Also please make sure you're using the latest version 10.5.2 before trying the workaround.

**Comment by yousefhamza** [comment]
@ashiemke 
Feel free to open this if you still encounter this issue
