### ISSUE TITLE
'... all-product-headers.yaml' not found, breaks the debugger

### ISSUE THREAD

**Issue by hingarn** [Instabug/Instabug-iOS#427]
### Steps to Reproduce the Problem
Happens after every app launch (looks similar to https://github.com/Instabug/Instabug-iOS/issues/368)

### Expected Behavior
Typing `po variableName` in the Xcode console would output debug information

### Actual Behavior
```
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/Instabug-cvgnxykmqaptlvcvhwtspqfbequo/Build/Intermediates.noindex/ArchiveIntermediates/InstabugDynamic/IntermediateBuildFilesPath/Instabug.build/Release-iphonesimulator/InstabugDynamic.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

### Instabug integration code
```
CrashReporting.enabled = false
Instabug.start(withToken: "", invocationEvents: [.shake])
Instabug.welcomeMessageMode = IBGWelcomeMessageMode.disabled
Instabug.tintColor = UIColor.color
```

### SDK Version
Any version greater than 10.5.2 (works as expected on 10.5.2)

### iOS Version
14.5

### Device Model
iPhone 12 Simulator

**Comment by husseinkishk** [comment]
@hingarn
This is an issue in lldb, which happens sometimes when you are trying to integrate Instabug in a Swift-only project.

A workaround for this issue is to add Objective-C files and a bridging header to your project, like mentioned in this [StackOverflow post](https://stackoverflow.com/questions/54776459/whats-the-solution-for-error-couldnt-irgen-expression-no-additional-error/61824142#61824142).

Also please make sure you're using the latest version 10.7.2 before trying the workaround.

**Comment by hingarn** [comment]
Thank you, @husseinkishk, can confirm that adding a bridging header works.

**Comment by tinder-owenthomas** [comment]
@husseinkishk Adding objective C to our targets is not a great work around as it increases build times/complexity. We are actively attempting to remove Objc from all of our targets so we won't be able to use this work around. We've found that pinning Instabug at 10.5.2 "solves" the issue, so it seems something has changed in Instabug after that which causes this issue. Is there any chance we can try to get it resolved in Instabug itself so we can continue updating to the latest version?

**Comment by yousefhamza** [comment]
@tinder-owenthomas which Instabug version you are using now?

It looks like this issue was related to us using Xcode 12.5 to build the SDK but then we reverted back and users have reported the problem solved, so if you are not using the latest, please do, and let us know if you still have any problems.

**Comment by dweekly** [comment]
It looks like this issue is happening with XCode 13.3 and Instabug 10.13.0, just ran into this. I'll try the workaround.

error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/Instabug-cvgnxykmqaptlvcvhwtspqfbequo/Build/Intermediates.noindex/ArchiveIntermediates/InstabugDynamic/IntermediateBuildFilesPath/Instabug.build/Release-iphoneos/InstabugDynamic.build/all-product-headers.yaml' not found

**Comment by hingarn** [comment]
Yes, seeing this issue again as well with XCode 13.3 and Instabug 10.13.0.

**Comment by husseinkishk** [comment]
Sorry for seeing this again. The problem A release is coming up very soon to fix this.

**Comment by husseinkishk** [comment]
Please find the fix in Instabug v10.13.1
Thank you for your patience.

**Comment by KerollosNabil** [comment]
We are sorry for being late 
can you please tell me which Xcode version you use?

**Comment by JiBB** [comment]
13.2.1

**Comment by JiBB** [comment]
13.2.1

**Comment by KerollosNabil** [comment]
sorry for your wait but after investigation we found that
the problem is with Xcode version 13.2.1
you should have a higher version of Xcode and everything will work okay
