### ISSUE TITLE
Strange crash with IBGMethodSwizzler

### ISSUE THREAD

**Issue by ZedsDead** [Instabug/Instabug-iOS#48]
![crash_log](https://cloud.githubusercontent.com/assets/3908195/12482029/502912a0-c05e-11e5-9c3c-5a98e86ca196.png)
![crash_stats](https://cloud.githubusercontent.com/assets/3908195/12482030/5055e992-c05e-11e5-9934-80a130e51557.png)

**Comment by msoliman** [comment]
@ZedsDead looks like the crash is in the `[UIApplication sendEvent:]`. You'll find Instabug in the stack trace there because the SDK logs the `sendEvent` method calls to track the user steps. However in the implementation of the `[IBGMethodSwizzler sendEvent:]` it just logs the event then calls the original `[UIApplication sendEvent:]`. As you can see in the stack trace, the crash isn't in the logging part, it's in the original method call.
Does that make sense?

**Comment by ZedsDead** [comment]
@msoliman there is no much information in the internet. But yeah, that has sense..
