### ISSUE TITLE
Instabug posts a lot of [Instabug] logs into console

### ISSUE THREAD

**Issue by nezhyborets** [Instabug/Instabug-iOS#481]
His guys, this is kind of an issue for me as I this burdens my logs a lot. I would like to fix all those warnings, but I'm not sure they are actionable for me.

### Steps to Reproduce the Problem
I basically just run the app and login to my user.

### Expected Behavior
There are some informative logs that I can act upon.

### Actual Behavior
There are a lot of Instabug logs and I have no idea what I can do about them

### Instabug integration code
```swift
private func setupInstabug() {
    Instabug.start(withToken: Constants.configuration.instabugToken,
                   invocationEvents: [.none])
    Instabug.welcomeMessageMode = .disabled
    Instabug.tintColor = .mainColor()
    
    if Locale.current.languageCode == "uk", Locale.preferredLanguages[safe: 1]?.contains("ru") == true {
        Instabug.setLocale(.russian)
    }
    
    BugReporting.enabledAttachmentTypes = [.extraScreenShot, .galleryImage, .screenRecording]
}
```

### SDK Version
12.2.0

### iOS Version
15.0

### Device Model
iOS Simulator - iPhone 15 Pro Max

### Example log file
[Instabug.zip](https://github.com/Instabug/Instabug-iOS/files/13441144/Instabug.zip)

Thanks!

**Comment by ahmedsalah196** [comment]
Hello @nezhyborets, I hope you're having a great day.
First, let me explain the meaning of those errors/warnings. 90% of them are because your network requests' size exceeds our limit for network logs. We'll work on enhancing this in our next releases.

If you need a temporary workaround for this, you can control our logging level through [this API](https://docs.instabug.com/reference/instabug-logs).

I hope this helps,
Thanks 🙏

**Comment by nezhyborets** [comment]
Hi @ahmedsalah196 and thanks so much for quick response!

Oh, I see, probably my bad, I didn't even know that Instabug does some automatic network logging. I integrated it only for bug reporting purposes. 

As I see here https://docs.instabug.com/reference/network-logging-ios, I can disable them, which is ok for my case. Thanks!
