### ISSUE TITLE
Instabug crashes on the latest version

### ISSUE THREAD

**Issue by pnhoang** [Instabug/Instabug-iOS#54]
It is a crash by integrating Instabug from CocoaPods. 

I have these lines in Podfile:

platform :ios, '7.0'
source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/Accengage/CocoaPodsSpecs.git"

pod "Instabug"

After doing $ pod install, I have version 5.1.0

It's in [IBGBaseHUD show] method.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteMutableAttributedString initWithString:: nil value'
*** First throw call stack:
(0x182835900 0x181ea3f80 0x182835848 0x183118da4 0x100470ae0 0x100554e4c 0x100e79bf0 0x100e79bb0 0x100e85e3c 0x100e79bb0 0x100e91f54 0x100e7c154 0x100e7f034 0x1827ecbb0 0x1827eaa18 0x182719680 0x183c28088 0x187590d90 0x1001647f8 0x1822ba8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by msoliman** [comment]
@pnhoang how about the bug reporting. Are you able to invoke the SDK and go through the bug reporting process successfully?

**Comment by pnhoang** [comment]
Instabug itself just crashes and makes the app crash. I use an earlier of the version and it does not crash anymore. Hope you figure out what's the reason. We use Instabug a lot, we do see the crashes from Instabug, but it turned out to be from Instabug library. Somehow the bundle was not copied into the project from the Pod. If we copy the project framework into our project, it works. And it also works if we switch to an earlier version such as 4.1.4, not the latest one. Please investigate.

**Comment by msoliman** [comment]
Thanks @pnhoang so you are able to get it to work when you manually add the .bundle in, right?

**Comment by pnhoang** [comment]
yes it is true.

**Comment by pnhoang** [comment]
I can easily reproduce the crashes, if you have Skype, I can show it to you via share screen. we have some more dependencies with other Pods.

**Comment by msoliman** [comment]
It makes sense actually. Once the bundle isn't there, it makes sense that all these crashes happen.
It's just weird that the bundle file isn't included automatically when you do a `pod install`, Does it help to do a clean build or re-run the pod install?

**Comment by pnhoang** [comment]
it was not included somehow. All of us in the team have the same thing and we already clean the whole project, re-run pod install so many times. It does not have any effect.

**Comment by pnhoang** [comment]
any news on this @msoliman @Instabug ? thanks.

**Comment by msoliman** [comment]
@pnhoang we're still looking into this. Is it currently blocking you or are you able to get it to work by manually adding the .bundle file?

**Comment by nekonari** [comment]
I'm seeing exact same issue. I wasted 3 hours on this... Any update on the fix?

**Comment by pnhoang** [comment]
if you manually copy the bundle to the project, then it will work. this problem does not occur any more with the latest version. double check if you use the latest version from their available pods.

**Comment by stansey** [comment]
What is the "latest version" (The one that worked). The latest version of instabug available 7/19/16 was 5.3?

I am seeing a possibly similar crash. We upgraded from Instabug 5.2.2 to Instabug 7.2.8

I don't want to manually copy the bundle files because I have automated the process of building the ipa. I'm nervous about further automating workarounds for cocoapods. I am using cocoapods version 1.1.1 (Because cocoapods 1.2 has bugs that prevent it from building my app). I'm going to try different versions of cocoapods. 

![screen shot 2017-06-28 at 1 39 45 pm](https://user-images.githubusercontent.com/3424172/27659335-efa6e80c-5c07-11e7-9848-fb5616a76f6e.png)

**Comment by Kmohamed** [comment]
@stansey let me check it and get back to you soon.

**Comment by stansey** [comment]
We found a fix. A while back we added an automated step that would remove the "Embed Pods Framework" build phase before we packaged our app. This was necessary or uploading our app to the iTunes Connect would fail (possibly due to the presence of an empty directory or something like that?) But our app no longer fails to upload to iTunes Connect when we leave the "Embed Pods Framework" build phase in. Removing that hack (deleting "Embed..." build phase) allows us to upload and distribute our app with the new version of Instabug.

**Comment by Kmohamed** [comment]
@stansey Great but I am curious why do you want to remove "Embed Pods Framework" ?

**Comment by stansey** [comment]
We used to have to remove the "Embed Pods Frameworks" build phase or our app would get rejected when we tried to upload it to iTunes Connect. I don't understand why that was the case. That doesn't happen now though, so it's not a problem any more.

**Comment by Kmohamed** [comment]
Could you send to me this error ?
