### ISSUE TITLE
Exclude localizations when installing via Cocoapods?

### ISSUE THREAD

**Issue by dmur** [Instabug/Instabug-iOS#92]
Hi there,

When installing the SDK via Cocoapods, all localizations are included. The App Store automatically detects languages upon app submission based on which localization files are present. This means that any app with Instabug installed will be listed in the App Store as supporting all languages which the Instabug SDK supports.

The workaround is currently to go through the Instabug.bundle contents and delete all localizations which the app itself does not support before submitting to the App Store. Of course, modifying the installed pod defeats the purpose of using Cocoapods at all. It would be better if there were some way to specify in the Podfile which languages you'd like to be installed with the Instabug SDK. This could be achieved using [subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec). I'd imagine it'd work something like this:

`pod 'Instabug/EN'`

**Comment by HeshamMegid** [comment]
Hi @dmur,

Have you been able to verify that this is caused by Instabug? I have submitted several test builds to iTunes Connect with Instabug installed via Cocoapods using different configurations to try to reproduce this issue but I was unable to do so.

What else do you have in your `podfile` if you don't mind sharing.

**Comment by dmur** [comment]
Hi @HeshamMegid,

Thanks for the prompt reply. I do believe this is caused by Instabug. When submitting our latest build to the App Store, we received this notification upon submission:

<img width="499" alt="screen shot 2016-11-01 at 5 16 25 pm" src="https://cloud.githubusercontent.com/assets/1051674/19912378/411689b2-a057-11e6-8824-0a386add1c3c.png">

I will confirm the languages are updated in the App Store description once the build is live.

For reference, here are the full Podfile dependencies:

```
pod 'Instabug'
pod 'Google/Analytics'
pod 'GoogleIDFASupport'
pod 'React', :path => './node_modules/react-native', :subspecs => %w(
    Core
    RCTText
    RCTWebSocket
    RCTImage
)
pod 'CodePush', :path => './node_modules/react-native-code-push'
pod 'FormatterKit'
pod 'BugfenderSDK'
```

**Comment by HeshamMegid** [comment]
@dmur, this issue is caused by `FormatterKit` since its .lproj files are not added to a separate bundle. Check this issue: https://github.com/mattt/FormatterKit/issues/88

By the way, you can check the build languages in iTunes Connect before it has been accepted into the App Store. Check Store Information under the Activity tab.
